//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGogglesCare.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLens
    {
        public long ProductLensesId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> LensesId { get; set; }
    
        public virtual LensesType LensesType { get; set; }
        public virtual Product Product { get; set; }
    }
}
