//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGogglesCare.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOption
    {
        public long ProductOptionsId { get; set; }
        public Nullable<long> CT_OptionId { get; set; }
        public Nullable<long> ProductId { get; set; }
    
        public virtual CT_Option CT_Option { get; set; }
        public virtual Product Product { get; set; }
    }
}
